defaultPortal: 9amHealthPROD
portals:
  - name: 9amHealthPROD
    portalId: 21917313
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CMqNtcLoMBIIAA0AAAAAAAwYgd25CiDio7YVKO7pDDIU7nTJc-lifqPqWiTIeNt-vRmwE1A6KAAABEEAAAB4AAAAAAAAAAAAAAAAAAAABAAAwAcAAAAAPAAAAAAAAGBCFMcp6glPtryD7hls87KsRrnyoMMxSgNuYTFSAFoA
        expiresAt: '2023-02-25T11:20:11.210Z'
    personalAccessKey: >-
      CiQ4N2Y2ZDI3MC0wZTk4LTRhMjgtYTRiMi04ODU1NjQ1YjdiYzEQgd25Chjio7YVKhkABeaRgplqhAREujkVazPlaQsPPQQxaLQ4SgNuYTE
    sandboxAccountType: null
    parentAccountId: null
