packages:
  - apps/*
  - packages/*
  - packages/plugins/*/*

catalog:
  '@testing-library/dom': ^10.4.1
  '@testing-library/jest-dom': ^6.6.4
  '@testing-library/user-event': ^14.6.1
  '@types/bun': ^1.2.19
  '@types/node': ^24.1.0
  '@types/react': ^19.1.9
  happy-dom: ^18.0.1
  jsdom: ^26.1.0
  react: ^19.1.1
  react-dom: ^19.1.1
  typescript: ^5.9.2
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plugin-dts: ^4.5.4
  publint: ^0.3.12
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
