export interface SearchItem {
  id: string;
  name: string;
  description: string;
  category: string;
  tags: string[];
}

export const SEARCH_DATA: SearchItem[] = [
  // Electronics
  {
    id: '1',
    name: 'Wireless Headphones',
    description: 'High-quality audio with active noise cancellation',
    category: 'Electronics',
    tags: ['audio', 'wireless', 'bluetooth'],
  },
  {
    id: '2',
    name: 'Ergonomic Keyboard',
    description: 'Mechanical keyboard with wrist support',
    category: 'Electronics',
    tags: ['typing', 'mechanical', 'ergonomic'],
  },
  {
    id: '3',
    name: 'USB-C Monitor',
    description: '4K display with USB-C power delivery',
    category: 'Electronics',
    tags: ['display', '4k', 'usb-c'],
  },
  {
    id: '4',
    name: 'Wireless Mouse',
    description: 'Precision optical mouse with rechargeable battery',
    category: 'Electronics',
    tags: ['mouse', 'wireless', 'ergonomic'],
  },
  {
    id: '5',
    name: 'Webcam HD',
    description: '1080p webcam with auto-focus',
    category: 'Electronics',
    tags: ['video', 'webcam', '1080p'],
  },
  {
    id: '6',
    name: 'Bluetooth Speaker',
    description: 'Portable speaker with 12-hour battery life',
    category: 'Electronics',
    tags: ['audio', 'bluetooth', 'portable'],
  },
  {
    id: '7',
    name: 'External SSD',
    description: '1TB portable SSD with USB 3.2',
    category: 'Electronics',
    tags: ['storage', 'ssd', 'portable'],
  },
  {
    id: '8',
    name: 'Mechanical Numpad',
    description: 'Standalone mechanical numpad',
    category: 'Electronics',
    tags: ['keyboard', 'numpad', 'mechanical'],
  },
  {
    id: '9',
    name: 'USB Hub',
    description: '7-port USB 3.0 hub with power adapter',
    category: 'Electronics',
    tags: ['usb', 'hub', 'connectivity'],
  },
  {
    id: '10',
    name: 'Desk Lamp LED',
    description: 'Adjustable LED lamp with USB charging',
    category: 'Electronics',
    tags: ['lighting', 'led', 'adjustable'],
  },

  // Furniture
  {
    id: '11',
    name: 'Standing Desk',
    description: 'Adjustable height standing desk',
    category: 'Furniture',
    tags: ['desk', 'ergonomic', 'adjustable'],
  },
  {
    id: '12',
    name: 'Office Chair',
    description: 'Comfortable mesh office chair',
    category: 'Furniture',
    tags: ['chair', 'ergonomic', 'mesh'],
  },
  {
    id: '13',
    name: 'Bookshelf',
    description: '5-tier wooden bookshelf',
    category: 'Furniture',
    tags: ['storage', 'books', 'wooden'],
  },
  {
    id: '14',
    name: 'Filing Cabinet',
    description: '3-drawer metal filing cabinet',
    category: 'Furniture',
    tags: ['storage', 'filing', 'office'],
  },
  {
    id: '15',
    name: 'Monitor Stand',
    description: 'Wooden monitor stand with storage',
    category: 'Furniture',
    tags: ['desk', 'monitor', 'storage'],
  },
  {
    id: '16',
    name: 'Desk Organizer',
    description: 'Bamboo desk organizer with compartments',
    category: 'Furniture',
    tags: ['organization', 'desk', 'bamboo'],
  },
  {
    id: '17',
    name: 'Side Table',
    description: 'Small side table with drawer',
    category: 'Furniture',
    tags: ['table', 'storage', 'drawer'],
  },
  {
    id: '18',
    name: 'Footrest',
    description: 'Ergonomic footrest with massage rollers',
    category: 'Furniture',
    tags: ['ergonomic', 'comfort', 'footrest'],
  },

  // Accessories
  {
    id: '19',
    name: 'Laptop Stand',
    description: 'Aluminum laptop stand with cooling',
    category: 'Accessories',
    tags: ['laptop', 'stand', 'cooling'],
  },
  {
    id: '20',
    name: 'Phone Holder',
    description: 'Adjustable phone holder for desk',
    category: 'Accessories',
    tags: ['phone', 'holder', 'adjustable'],
  },
  {
    id: '21',
    name: 'Cable Management Kit',
    description: 'Cable clips and sleeves for desk organization',
    category: 'Accessories',
    tags: ['cables', 'organization', 'clips'],
  },
  {
    id: '22',
    name: 'Wrist Rest',
    description: 'Memory foam wrist rest for keyboard',
    category: 'Accessories',
    tags: ['ergonomic', 'comfort', 'foam'],
  },
  {
    id: '23',
    name: 'Mouse Pad',
    description: 'Large extended gaming mouse pad',
    category: 'Accessories',
    tags: ['mouse', 'pad', 'gaming'],
  },
  {
    id: '24',
    name: 'Headset Stand',
    description: 'RGB headset stand with USB ports',
    category: 'Accessories',
    tags: ['headset', 'stand', 'usb'],
  },
  {
    id: '25',
    name: 'Monitor Light Bar',
    description: 'USB-powered monitor light bar',
    category: 'Accessories',
    tags: ['lighting', 'monitor', 'usb'],
  },
  {
    id: '26',
    name: 'Laptop Sleeve',
    description: 'Padded laptop sleeve 15 inch',
    category: 'Accessories',
    tags: ['laptop', 'protection', 'sleeve'],
  },
  {
    id: '27',
    name: 'Cleaning Kit',
    description: 'Screen cleaning kit with microfiber cloth',
    category: 'Accessories',
    tags: ['cleaning', 'screen', 'maintenance'],
  },

  // Books
  {
    id: '28',
    name: 'Clean Code',
    description: 'A handbook of agile software craftsmanship',
    category: 'Books',
    tags: ['programming', 'software', 'clean-code'],
  },
  {
    id: '29',
    name: 'Design Patterns',
    description: 'Elements of reusable object-oriented software',
    category: 'Books',
    tags: ['programming', 'patterns', 'architecture'],
  },
  {
    id: '30',
    name: 'The Pragmatic Programmer',
    description: 'Your journey to mastery',
    category: 'Books',
    tags: ['programming', 'career', 'best-practices'],
  },
  {
    id: '31',
    name: 'Refactoring',
    description: 'Improving the design of existing code',
    category: 'Books',
    tags: ['programming', 'refactoring', 'code-quality'],
  },
  {
    id: '32',
    name: 'JavaScript: The Good Parts',
    description: 'Unearthing the excellence in JavaScript',
    category: 'Books',
    tags: ['javascript', 'programming', 'web'],
  },
  {
    id: '33',
    name: "You Don't Know JS",
    description: 'Deep dive into JavaScript fundamentals',
    category: 'Books',
    tags: ['javascript', 'programming', 'fundamentals'],
  },
  {
    id: '34',
    name: 'Domain-Driven Design',
    description: 'Tackling complexity in the heart of software',
    category: 'Books',
    tags: ['architecture', 'design', 'ddd'],
  },
  {
    id: '35',
    name: 'Test-Driven Development',
    description: 'By example',
    category: 'Books',
    tags: ['testing', 'tdd', 'programming'],
  },
  {
    id: '36',
    name: 'Continuous Delivery',
    description: 'Reliable software releases through automation',
    category: 'Books',
    tags: ['devops', 'automation', 'deployment'],
  },
  {
    id: '37',
    name: 'The Phoenix Project',
    description: 'A novel about IT, DevOps, and helping your business win',
    category: 'Books',
    tags: ['devops', 'it', 'management'],
  },

  // Software
  {
    id: '38',
    name: 'IDE Subscription',
    description: 'Professional IDE with refactoring tools',
    category: 'Software',
    tags: ['development', 'ide', 'tools'],
  },
  {
    id: '39',
    name: 'Design Tool License',
    description: 'Vector graphics and UI design software',
    category: 'Software',
    tags: ['design', 'graphics', 'ui'],
  },
  {
    id: '40',
    name: 'Password Manager',
    description: 'Secure password manager with 2FA',
    category: 'Software',
    tags: ['security', 'passwords', '2fa'],
  },
  {
    id: '41',
    name: 'VPN Service',
    description: 'Secure VPN with multiple server locations',
    category: 'Software',
    tags: ['security', 'vpn', 'privacy'],
  },
  {
    id: '42',
    name: 'Cloud Storage',
    description: '2TB cloud storage with file sync',
    category: 'Software',
    tags: ['storage', 'cloud', 'backup'],
  },
  {
    id: '43',
    name: 'Video Editor',
    description: 'Professional video editing software',
    category: 'Software',
    tags: ['video', 'editing', 'media'],
  },
  {
    id: '44',
    name: 'Screen Recording',
    description: 'Screen recording and editing tool',
    category: 'Software',
    tags: ['recording', 'screen', 'video'],
  },
  {
    id: '45',
    name: 'API Testing Tool',
    description: 'REST API testing and documentation',
    category: 'Software',
    tags: ['api', 'testing', 'development'],
  },
  {
    id: '46',
    name: 'Database Tool',
    description: 'Universal database client',
    category: 'Software',
    tags: ['database', 'sql', 'development'],
  },
  {
    id: '47',
    name: 'Note-Taking App',
    description: 'Markdown-based note-taking with sync',
    category: 'Software',
    tags: ['notes', 'markdown', 'productivity'],
  },
  {
    id: '48',
    name: 'Time Tracking',
    description: 'Time tracking and productivity tool',
    category: 'Software',
    tags: ['productivity', 'time', 'tracking'],
  },
  {
    id: '49',
    name: 'Backup Software',
    description: 'Automated backup solution',
    category: 'Software',
    tags: ['backup', 'security', 'automation'],
  },
  {
    id: '50',
    name: 'Terminal Emulator',
    description: 'Modern terminal with tabs and themes',
    category: 'Software',
    tags: ['terminal', 'development', 'cli'],
  },
  {
    id: '51',
    name: 'Git Client',
    description: 'Visual git client with merge tools',
    category: 'Software',
    tags: ['git', 'development', 'version-control'],
  },
  {
    id: '52',
    name: 'Markdown Editor',
    description: 'Distraction-free markdown writing',
    category: 'Software',
    tags: ['markdown', 'writing', 'productivity'],
  },
];

export const CATEGORIES = [
  'All',
  'Electronics',
  'Furniture',
  'Accessories',
  'Books',
  'Software',
];
