/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DocsImport } from './routes/docs'
import { Route as DemoImport } from './routes/demo'
import { Route as IndexImport } from './routes/index'
import { Route as DocsIndexImport } from './routes/docs/index'
import { Route as DocsIntroductionImport } from './routes/docs/introduction'
import { Route as DocsInstallationImport } from './routes/docs/installation'
import { Route as DocsCoreConceptsImport } from './routes/docs/core-concepts'
import { Route as DemoTaskboardImport } from './routes/demo/taskboard'
import { Route as DemoPetfinderImport } from './routes/demo/petfinder'
import { Route as DemoInstanceManagementImport } from './routes/demo/instance-management'
import { Route as DemoDependencyTrackingImport } from './routes/demo/dependency-tracking'
import { Route as DemoCounterImport } from './routes/demo/counter'
import { Route as DocsBlacReactUseBlocImport } from './routes/docs/blac-react/use-bloc'
import { Route as DocsBlacNextCubitImport } from './routes/docs/blac-next/cubit'

// Create/Update Routes

const DocsRoute = DocsImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRoute,
} as any)

const DemoRoute = DemoImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DocsIndexRoute = DocsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)

const DocsIntroductionRoute = DocsIntroductionImport.update({
  id: '/introduction',
  path: '/introduction',
  getParentRoute: () => DocsRoute,
} as any)

const DocsInstallationRoute = DocsInstallationImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRoute,
} as any)

const DocsCoreConceptsRoute = DocsCoreConceptsImport.update({
  id: '/core-concepts',
  path: '/core-concepts',
  getParentRoute: () => DocsRoute,
} as any)

const DemoTaskboardRoute = DemoTaskboardImport.update({
  id: '/taskboard',
  path: '/taskboard',
  getParentRoute: () => DemoRoute,
} as any)

const DemoPetfinderRoute = DemoPetfinderImport.update({
  id: '/petfinder',
  path: '/petfinder',
  getParentRoute: () => DemoRoute,
} as any)

const DemoInstanceManagementRoute = DemoInstanceManagementImport.update({
  id: '/instance-management',
  path: '/instance-management',
  getParentRoute: () => DemoRoute,
} as any)

const DemoDependencyTrackingRoute = DemoDependencyTrackingImport.update({
  id: '/dependency-tracking',
  path: '/dependency-tracking',
  getParentRoute: () => DemoRoute,
} as any)

const DemoCounterRoute = DemoCounterImport.update({
  id: '/counter',
  path: '/counter',
  getParentRoute: () => DemoRoute,
} as any)

const DocsBlacReactUseBlocRoute = DocsBlacReactUseBlocImport.update({
  id: '/blac-react/use-bloc',
  path: '/blac-react/use-bloc',
  getParentRoute: () => DocsRoute,
} as any)

const DocsBlacNextCubitRoute = DocsBlacNextCubitImport.update({
  id: '/blac-next/cubit',
  path: '/blac-next/cubit',
  getParentRoute: () => DocsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoImport
      parentRoute: typeof rootRoute
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsImport
      parentRoute: typeof rootRoute
    }
    '/demo/counter': {
      id: '/demo/counter'
      path: '/counter'
      fullPath: '/demo/counter'
      preLoaderRoute: typeof DemoCounterImport
      parentRoute: typeof DemoImport
    }
    '/demo/dependency-tracking': {
      id: '/demo/dependency-tracking'
      path: '/dependency-tracking'
      fullPath: '/demo/dependency-tracking'
      preLoaderRoute: typeof DemoDependencyTrackingImport
      parentRoute: typeof DemoImport
    }
    '/demo/instance-management': {
      id: '/demo/instance-management'
      path: '/instance-management'
      fullPath: '/demo/instance-management'
      preLoaderRoute: typeof DemoInstanceManagementImport
      parentRoute: typeof DemoImport
    }
    '/demo/petfinder': {
      id: '/demo/petfinder'
      path: '/petfinder'
      fullPath: '/demo/petfinder'
      preLoaderRoute: typeof DemoPetfinderImport
      parentRoute: typeof DemoImport
    }
    '/demo/taskboard': {
      id: '/demo/taskboard'
      path: '/taskboard'
      fullPath: '/demo/taskboard'
      preLoaderRoute: typeof DemoTaskboardImport
      parentRoute: typeof DemoImport
    }
    '/docs/core-concepts': {
      id: '/docs/core-concepts'
      path: '/core-concepts'
      fullPath: '/docs/core-concepts'
      preLoaderRoute: typeof DocsCoreConceptsImport
      parentRoute: typeof DocsImport
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationImport
      parentRoute: typeof DocsImport
    }
    '/docs/introduction': {
      id: '/docs/introduction'
      path: '/introduction'
      fullPath: '/docs/introduction'
      preLoaderRoute: typeof DocsIntroductionImport
      parentRoute: typeof DocsImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexImport
      parentRoute: typeof DocsImport
    }
    '/docs/blac-next/cubit': {
      id: '/docs/blac-next/cubit'
      path: '/blac-next/cubit'
      fullPath: '/docs/blac-next/cubit'
      preLoaderRoute: typeof DocsBlacNextCubitImport
      parentRoute: typeof DocsImport
    }
    '/docs/blac-react/use-bloc': {
      id: '/docs/blac-react/use-bloc'
      path: '/blac-react/use-bloc'
      fullPath: '/docs/blac-react/use-bloc'
      preLoaderRoute: typeof DocsBlacReactUseBlocImport
      parentRoute: typeof DocsImport
    }
  }
}

// Create and export the route tree

interface DemoRouteChildren {
  DemoCounterRoute: typeof DemoCounterRoute
  DemoDependencyTrackingRoute: typeof DemoDependencyTrackingRoute
  DemoInstanceManagementRoute: typeof DemoInstanceManagementRoute
  DemoPetfinderRoute: typeof DemoPetfinderRoute
  DemoTaskboardRoute: typeof DemoTaskboardRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoCounterRoute: DemoCounterRoute,
  DemoDependencyTrackingRoute: DemoDependencyTrackingRoute,
  DemoInstanceManagementRoute: DemoInstanceManagementRoute,
  DemoPetfinderRoute: DemoPetfinderRoute,
  DemoTaskboardRoute: DemoTaskboardRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface DocsRouteChildren {
  DocsCoreConceptsRoute: typeof DocsCoreConceptsRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsIntroductionRoute: typeof DocsIntroductionRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsBlacNextCubitRoute: typeof DocsBlacNextCubitRoute
  DocsBlacReactUseBlocRoute: typeof DocsBlacReactUseBlocRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsCoreConceptsRoute: DocsCoreConceptsRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsIntroductionRoute: DocsIntroductionRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsBlacNextCubitRoute: DocsBlacNextCubitRoute,
  DocsBlacReactUseBlocRoute: DocsBlacReactUseBlocRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/demo/counter': typeof DemoCounterRoute
  '/demo/dependency-tracking': typeof DemoDependencyTrackingRoute
  '/demo/instance-management': typeof DemoInstanceManagementRoute
  '/demo/petfinder': typeof DemoPetfinderRoute
  '/demo/taskboard': typeof DemoTaskboardRoute
  '/docs/core-concepts': typeof DocsCoreConceptsRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/introduction': typeof DocsIntroductionRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/blac-next/cubit': typeof DocsBlacNextCubitRoute
  '/docs/blac-react/use-bloc': typeof DocsBlacReactUseBlocRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/counter': typeof DemoCounterRoute
  '/demo/dependency-tracking': typeof DemoDependencyTrackingRoute
  '/demo/instance-management': typeof DemoInstanceManagementRoute
  '/demo/petfinder': typeof DemoPetfinderRoute
  '/demo/taskboard': typeof DemoTaskboardRoute
  '/docs/core-concepts': typeof DocsCoreConceptsRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/introduction': typeof DocsIntroductionRoute
  '/docs': typeof DocsIndexRoute
  '/docs/blac-next/cubit': typeof DocsBlacNextCubitRoute
  '/docs/blac-react/use-bloc': typeof DocsBlacReactUseBlocRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/demo/counter': typeof DemoCounterRoute
  '/demo/dependency-tracking': typeof DemoDependencyTrackingRoute
  '/demo/instance-management': typeof DemoInstanceManagementRoute
  '/demo/petfinder': typeof DemoPetfinderRoute
  '/demo/taskboard': typeof DemoTaskboardRoute
  '/docs/core-concepts': typeof DocsCoreConceptsRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/introduction': typeof DocsIntroductionRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/blac-next/cubit': typeof DocsBlacNextCubitRoute
  '/docs/blac-react/use-bloc': typeof DocsBlacReactUseBlocRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/docs'
    | '/demo/counter'
    | '/demo/dependency-tracking'
    | '/demo/instance-management'
    | '/demo/petfinder'
    | '/demo/taskboard'
    | '/docs/core-concepts'
    | '/docs/installation'
    | '/docs/introduction'
    | '/docs/'
    | '/docs/blac-next/cubit'
    | '/docs/blac-react/use-bloc'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/demo/counter'
    | '/demo/dependency-tracking'
    | '/demo/instance-management'
    | '/demo/petfinder'
    | '/demo/taskboard'
    | '/docs/core-concepts'
    | '/docs/installation'
    | '/docs/introduction'
    | '/docs'
    | '/docs/blac-next/cubit'
    | '/docs/blac-react/use-bloc'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/docs'
    | '/demo/counter'
    | '/demo/dependency-tracking'
    | '/demo/instance-management'
    | '/demo/petfinder'
    | '/demo/taskboard'
    | '/docs/core-concepts'
    | '/docs/installation'
    | '/docs/introduction'
    | '/docs/'
    | '/docs/blac-next/cubit'
    | '/docs/blac-react/use-bloc'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/demo",
        "/docs"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/demo": {
      "filePath": "demo.tsx",
      "children": [
        "/demo/counter",
        "/demo/dependency-tracking",
        "/demo/instance-management",
        "/demo/petfinder",
        "/demo/taskboard"
      ]
    },
    "/docs": {
      "filePath": "docs.tsx",
      "children": [
        "/docs/core-concepts",
        "/docs/installation",
        "/docs/introduction",
        "/docs/",
        "/docs/blac-next/cubit",
        "/docs/blac-react/use-bloc"
      ]
    },
    "/demo/counter": {
      "filePath": "demo/counter.tsx",
      "parent": "/demo"
    },
    "/demo/dependency-tracking": {
      "filePath": "demo/dependency-tracking.tsx",
      "parent": "/demo"
    },
    "/demo/instance-management": {
      "filePath": "demo/instance-management.tsx",
      "parent": "/demo"
    },
    "/demo/petfinder": {
      "filePath": "demo/petfinder.tsx",
      "parent": "/demo"
    },
    "/demo/taskboard": {
      "filePath": "demo/taskboard.tsx",
      "parent": "/demo"
    },
    "/docs/core-concepts": {
      "filePath": "docs/core-concepts.tsx",
      "parent": "/docs"
    },
    "/docs/installation": {
      "filePath": "docs/installation.tsx",
      "parent": "/docs"
    },
    "/docs/introduction": {
      "filePath": "docs/introduction.tsx",
      "parent": "/docs"
    },
    "/docs/": {
      "filePath": "docs/index.tsx",
      "parent": "/docs"
    },
    "/docs/blac-next/cubit": {
      "filePath": "docs/blac-next/cubit.tsx",
      "parent": "/docs"
    },
    "/docs/blac-react/use-bloc": {
      "filePath": "docs/blac-react/use-bloc.tsx",
      "parent": "/docs"
    }
  }
}
ROUTE_MANIFEST_END */
