/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DemoImport } from './routes/demo'
import { Route as IndexImport } from './routes/index'
import { Route as DemoTaskboardImport } from './routes/demo/taskboard'
import { Route as DemoPetfinderImport } from './routes/demo/petfinder'
import { Route as DemoFormImport } from './routes/demo/form'
import { Route as DemoCounterImport } from './routes/demo/counter'

// Create/Update Routes

const DemoRoute = DemoImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DemoTaskboardRoute = DemoTaskboardImport.update({
  id: '/taskboard',
  path: '/taskboard',
  getParentRoute: () => DemoRoute,
} as any)

const DemoPetfinderRoute = DemoPetfinderImport.update({
  id: '/petfinder',
  path: '/petfinder',
  getParentRoute: () => DemoRoute,
} as any)

const DemoFormRoute = DemoFormImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => DemoRoute,
} as any)

const DemoCounterRoute = DemoCounterImport.update({
  id: '/counter',
  path: '/counter',
  getParentRoute: () => DemoRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoImport
      parentRoute: typeof rootRoute
    }
    '/demo/counter': {
      id: '/demo/counter'
      path: '/counter'
      fullPath: '/demo/counter'
      preLoaderRoute: typeof DemoCounterImport
      parentRoute: typeof DemoImport
    }
    '/demo/form': {
      id: '/demo/form'
      path: '/form'
      fullPath: '/demo/form'
      preLoaderRoute: typeof DemoFormImport
      parentRoute: typeof DemoImport
    }
    '/demo/petfinder': {
      id: '/demo/petfinder'
      path: '/petfinder'
      fullPath: '/demo/petfinder'
      preLoaderRoute: typeof DemoPetfinderImport
      parentRoute: typeof DemoImport
    }
    '/demo/taskboard': {
      id: '/demo/taskboard'
      path: '/taskboard'
      fullPath: '/demo/taskboard'
      preLoaderRoute: typeof DemoTaskboardImport
      parentRoute: typeof DemoImport
    }
  }
}

// Create and export the route tree

interface DemoRouteChildren {
  DemoCounterRoute: typeof DemoCounterRoute
  DemoFormRoute: typeof DemoFormRoute
  DemoPetfinderRoute: typeof DemoPetfinderRoute
  DemoTaskboardRoute: typeof DemoTaskboardRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoCounterRoute: DemoCounterRoute,
  DemoFormRoute: DemoFormRoute,
  DemoPetfinderRoute: DemoPetfinderRoute,
  DemoTaskboardRoute: DemoTaskboardRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/counter': typeof DemoCounterRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/petfinder': typeof DemoPetfinderRoute
  '/demo/taskboard': typeof DemoTaskboardRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/counter': typeof DemoCounterRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/petfinder': typeof DemoPetfinderRoute
  '/demo/taskboard': typeof DemoTaskboardRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/counter': typeof DemoCounterRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/petfinder': typeof DemoPetfinderRoute
  '/demo/taskboard': typeof DemoTaskboardRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/demo/counter'
    | '/demo/form'
    | '/demo/petfinder'
    | '/demo/taskboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/demo/counter'
    | '/demo/form'
    | '/demo/petfinder'
    | '/demo/taskboard'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/demo/counter'
    | '/demo/form'
    | '/demo/petfinder'
    | '/demo/taskboard'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/demo"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/demo": {
      "filePath": "demo.tsx",
      "children": [
        "/demo/counter",
        "/demo/form",
        "/demo/petfinder",
        "/demo/taskboard"
      ]
    },
    "/demo/counter": {
      "filePath": "demo/counter.tsx",
      "parent": "/demo"
    },
    "/demo/form": {
      "filePath": "demo/form.tsx",
      "parent": "/demo"
    },
    "/demo/petfinder": {
      "filePath": "demo/petfinder.tsx",
      "parent": "/demo"
    },
    "/demo/taskboard": {
      "filePath": "demo/taskboard.tsx",
      "parent": "/demo"
    }
  }
}
ROUTE_MANIFEST_END */
